package editorsystem

import (
	"testing"

	editorcomponent "github.com/milk9111/sidescroller/cmd/editor/component"
	editorio "github.com/milk9111/sidescroller/cmd/editor/io"
	"github.com/milk9111/sidescroller/cmd/editor/model"
	"github.com/milk9111/sidescroller/ecs"
	"github.com/milk9111/sidescroller/levels"
)

func TestEditorAreaSystemCreatesTransitionAndCapturesPropertyUndoOnce(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1, TransitionMode: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 3, CellY: 4})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one transition entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "transition" {
		t.Fatalf("expected transition entity, got %q", created.Type)
	}
	if created.ID == "" {
		t.Fatal("expected autogenerated transition id")
	}
	if got := entityStringPropValue(created, "enter_dir"); got != "down" {
		t.Fatalf("expected default enter_dir down, got %q", got)
	}
	if got, ok := entityLayerIndex(created.Props); !ok || got != 1 {
		t.Fatalf("expected layer 1, got %d (ok=%t)", got, ok)
	}

	_, input, _ := rawInputState(w)
	_, pointer, _ := pointerState(w)
	input.LeftJustPressed = false
	input.LeftDown = true
	pointer.CellX = 5
	pointer.CellY = 6
	system.Update(w)

	created = entities.Items[0]
	if toFloat(created.Props["w"]) != 3*TileSize || toFloat(created.Props["h"]) != 3*TileSize {
		t.Fatalf("expected 3x3 tile area, got w=%v h=%v", created.Props["w"], created.Props["h"])
	}

	_, actions, _ := actionState(w)
	_, selection, _ := entitySelectionState(w)
	input.LeftDown = false
	input.LeftJustReleased = true
	system.Update(w)
	input.LeftJustReleased = false
	actions.TransitionID = "door_a"
	actions.TransitionToLevel = "zone_b"
	actions.TransitionLinkedID = "door_b"
	actions.TransitionEnterDir = "left"
	actions.ApplyTransitionFields = true
	system.Update(w)
	actions.TransitionToLevel = "zone_c"
	actions.ApplyTransitionFields = true
	system.Update(w)

	created = entities.Items[0]
	if created.ID != "door_a" {
		t.Fatalf("expected updated id, got %q", created.ID)
	}
	if got := entityStringPropValue(created, "to_level"); got != "zone_c.json" {
		t.Fatalf("expected normalized to_level zone_c.json, got %q", got)
	}
	if got := entityStringPropValue(created, "linked_id"); got != "door_b" {
		t.Fatalf("expected linked id door_b, got %q", got)
	}
	if got := entityStringPropValue(created, "enter_dir"); got != "left" {
		t.Fatalf("expected enter_dir left, got %q", got)
	}
	_, undo, _ := undoState(w)
	if len(undo.Snapshots) != 2 {
		t.Fatalf("expected two snapshots total (create + first property edit), got %d", len(undo.Snapshots))
	}
	if !selection.PropertySnapshotDone {
		t.Fatal("expected property snapshot flag to remain set after edits")
	}
}

func TestEditorAreaSystemIgnoresAreasOnOtherLayers(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 0, TransitionMode: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, WorldX: 16, WorldY: 16})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{Items: []levels.Entity{{Type: "transition", X: 0, Y: 0, Props: map[string]interface{}{"w": float64(TileSize), "h": float64(TileSize), "layer": 1, "id": "t1", "enter_dir": "down"}}}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})

	baseLayer := ecs.CreateEntity(w)
	_ = ecs.Add(w, baseLayer, editorcomponent.LayerDataComponent.Kind(), &editorcomponent.LayerData{Name: "Layer 1", Order: 0, Active: true, Tiles: make([]int, 240), TilesetUsage: make([]*levels.TileInfo, 240)})
	upperLayer := ecs.CreateEntity(w)
	_ = ecs.Add(w, upperLayer, editorcomponent.LayerDataComponent.Kind(), &editorcomponent.LayerData{Name: "Layer 2", Order: 1, Active: true, Tiles: make([]int, 240), TilesetUsage: make([]*levels.TileInfo, 240)})

	NewEditorAreaSystem("").Update(w)

	_, selection, _ := entitySelectionState(w)
	if selection.HoveredIndex != -1 {
		t.Fatalf("expected off-layer area to be ignored, got hovered index %d", selection.HoveredIndex)
	}
	if selection.SelectedIndex != -1 {
		t.Fatalf("expected no selected area, got %d", selection.SelectedIndex)
	}
}

func TestEditorAreaSystemCreatesTrigger(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 2, TriggerMode: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 2, CellY: 3})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one trigger entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "trigger" {
		t.Fatalf("expected trigger entity, got %q", created.Type)
	}
	if created.ID == "" {
		t.Fatal("expected autogenerated trigger id")
	}
	if got, ok := entityLayerIndex(created.Props); !ok || got != 2 {
		t.Fatalf("expected layer 2, got %d (ok=%t)", got, ok)
	}
	if disabled, _ := created.Props["disabled"].(bool); disabled {
		t.Fatal("expected new trigger to default disabled=false")
	}

	_, input, _ := rawInputState(w)
	_, pointer, _ := pointerState(w)
	input.LeftJustPressed = false
	input.LeftDown = false
	input.LeftJustReleased = true
	pointer.CellX = 4
	pointer.CellY = 5
	system.Update(w)

	created = entities.Items[0]
	if created.ID == "" {
		t.Fatal("expected trigger to retain autogenerated id")
	}
	if got := entityStringPropValue(created, "id"); got != created.ID {
		t.Fatalf("expected props id to match entity id %q, got %q", created.ID, got)
	}
	if disabled, _ := created.Props["disabled"].(bool); disabled {
		t.Fatal("expected trigger disabled flag to remain false")
	}
	_, undo, _ := undoState(w)
	if len(undo.Snapshots) != 1 {
		t.Fatalf("expected one snapshot for trigger creation, got %d", len(undo.Snapshots))
	}
}

func TestEditorAreaSystemCreatesBreakableWall(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1, BreakableWallMode: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 4, CellY: 5})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one breakable wall entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "breakable_wall" {
		t.Fatalf("expected breakable_wall entity, got %q", created.Type)
	}
	if got := entityStringPropValue(created, "prefab"); got != "breakable_cracks.yaml" {
		t.Fatalf("expected breakable_cracks prefab, got %q", got)
	}
	if got, ok := entityLayerIndex(created.Props); !ok || got != 1 {
		t.Fatalf("expected layer 1, got %d (ok=%t)", got, ok)
	}

	_, input, _ := rawInputState(w)
	_, pointer, _ := pointerState(w)
	input.LeftJustPressed = false
	input.LeftDown = true
	pointer.CellX = 6
	pointer.CellY = 7
	system.Update(w)

	created = entities.Items[0]
	if toFloat(created.Props["w"]) != 3*TileSize || toFloat(created.Props["h"]) != 3*TileSize {
		t.Fatalf("expected 3x3 tile area, got w=%v h=%v", created.Props["w"], created.Props["h"])
	}
	_, undo, _ := undoState(w)
	if len(undo.Snapshots) != 1 {
		t.Fatalf("expected one snapshot for breakable wall creation, got %d", len(undo.Snapshots))
	}
}

func TestEditorAreaSystemCreatesAreaPrefabFromSharedComponent(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 1, CellY: 2})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{SelectedPath: "transition.yaml", SelectedType: "transition"})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabCatalogComponent.Kind(), &editorcomponent.PrefabCatalog{Items: []editorio.PrefabInfo{{
		Path:       "transition.yaml",
		EntityType: "transition",
		Components: map[string]any{"area_bounds": map[string]any{"bounds": map[string]any{"w": 32.0, "h": 32.0}}},
	}}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one area entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "transition" {
		t.Fatalf("expected transition area entity, got %q", created.Type)
	}
	if got := entityStringPropValue(created, "prefab"); got != "transition.yaml" {
		t.Fatalf("expected prefab transition.yaml, got %q", got)
	}
	if got := entityStringPropValue(created, "enter_dir"); got != "down" {
		t.Fatalf("expected default enter_dir down, got %q", got)
	}
}

func TestEditorAreaSystemCreatesBreakableWallFromAreaPrefabSelection(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 2, CellY: 3})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{SelectedPath: "breakable_cracks.yaml", SelectedType: "breakable_wall"})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabCatalogComponent.Kind(), &editorcomponent.PrefabCatalog{Items: []editorio.PrefabInfo{{
		Path:       "breakable_cracks.yaml",
		Name:       "breakable_cracks",
		EntityType: "breakable_wall",
		Components: map[string]any{"area_bounds": map[string]any{"bounds": map[string]any{"w": 32.0, "h": 32.0}}},
	}}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one breakable wall area entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "breakable_wall" {
		t.Fatalf("expected breakable_wall entity type, got %q", created.Type)
	}
	if got := entityStringPropValue(created, "prefab"); got != "breakable_cracks.yaml" {
		t.Fatalf("expected breakable_cracks prefab path, got %q", got)
	}
	if got, ok := entityLayerIndex(created.Props); !ok || got != 1 {
		t.Fatalf("expected layer 1, got %d (ok=%t)", got, ok)
	}

	_, input, _ := rawInputState(w)
	_, pointer, _ := pointerState(w)
	input.LeftJustPressed = false
	input.LeftDown = true
	pointer.CellX = 4
	pointer.CellY = 5
	system.Update(w)

	created = entities.Items[0]
	if toFloat(created.Props["w"]) != 3*TileSize || toFloat(created.Props["h"]) != 3*TileSize {
		t.Fatalf("expected dragged breakable wall area to become 3x3 tiles, got w=%v h=%v", created.Props["w"], created.Props["h"])
	}
}

func TestEditorAreaSystemUsesPlacementAreaBoundsFlagWhenCatalogEntryLacksComponents(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 2, CellY: 3})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{SelectedPath: "breakable_cracks.yaml", SelectedType: "breakable_wall", AreaBounds: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabCatalogComponent.Kind(), &editorcomponent.PrefabCatalog{Items: []editorio.PrefabInfo{{
		Path:       "breakable_cracks.yaml",
		Name:       "breakable_cracks",
		EntityType: "breakable_wall",
	}}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected area placement flag to create one area entity, got %d", len(entities.Items))
	}
	if entities.Items[0].Type != "breakable_wall" {
		t.Fatalf("expected breakable_wall area entity, got %q", entities.Items[0].Type)
	}
}

func TestEditorAreaSystemAppliesSelectedTileToAreaPrefabSpriteOverride(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1, SelectedTile: model.TileSelection{Path: "cableways_tile.png", Index: 0, TileW: 32, TileH: 32}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 2, CellY: 3})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{SelectedPath: "solid_tile_platform.yaml", SelectedType: "solid_tile_platform"})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabCatalogComponent.Kind(), &editorcomponent.PrefabCatalog{Items: []editorio.PrefabInfo{{
		Path:       "solid_tile_platform.yaml",
		Name:       "solid_tile_platform",
		EntityType: "solid_tile_platform",
		Components: map[string]any{
			"area_bounds": map[string]any{"bounds": map[string]any{"w": 32.0, "h": 32.0}},
			"sprite":      map[string]any{"use_source": true},
		},
	}}})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one solid tile platform area entity, got %d", len(entities.Items))
	}
	overrides := entityComponentOverrides(entities.Items[0].Props)
	if overrides == nil {
		t.Fatal("expected component overrides on placed solid tile platform")
	}
	sprite, ok := overrides["sprite"].(map[string]any)
	if !ok {
		t.Fatalf("expected sprite override map, got %+v", overrides["sprite"])
	}
	if sprite["image"] != "cableways_tile.png" {
		t.Fatalf("expected sprite image override cableways_tile.png, got %+v", sprite["image"])
	}
	if sprite["use_source"] != true {
		t.Fatalf("expected sprite use_source override true, got %+v", sprite["use_source"])
	}
	if toFloat(sprite["source_x"]) != 0 || toFloat(sprite["source_y"]) != 0 {
		t.Fatalf("expected sprite source origin 0,0, got %+v,%+v", sprite["source_x"], sprite["source_y"])
	}
	if toFloat(sprite["source_w"]) != 32 || toFloat(sprite["source_h"]) != 32 {
		t.Fatalf("expected sprite source size 32x32, got %+v,%+v", sprite["source_w"], sprite["source_h"])
	}
}

func entityStringPropValue(item levels.Entity, key string) string {
	if item.Props == nil {
		return ""
	}
	value, _ := item.Props[key].(string)
	return value
}
