package editorsystem

import (
	"testing"

	editorcomponent "github.com/milk9111/sidescroller/cmd/editor/component"
	"github.com/milk9111/sidescroller/ecs"
	"github.com/milk9111/sidescroller/levels"
)

func TestEditorAreaSystemCreatesTransitionAndCapturesPropertyUndoOnce(t *testing.T) {
	w := ecs.NewWorld()
	sessionEntity := ecs.CreateEntity(w)
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorSessionComponent.Kind(), &editorcomponent.EditorSession{CurrentLayer: 1, TransitionMode: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelMetaComponent.Kind(), &editorcomponent.LevelMeta{Width: 20, Height: 12})
	_ = ecs.Add(w, sessionEntity, editorcomponent.RawInputStateComponent.Kind(), &editorcomponent.RawInputState{LeftJustPressed: true, LeftDown: true})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PointerStateComponent.Kind(), &editorcomponent.PointerState{InCanvas: true, HasCell: true, CellX: 3, CellY: 4})
	_ = ecs.Add(w, sessionEntity, editorcomponent.LevelEntitiesComponent.Kind(), &editorcomponent.LevelEntities{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.PrefabPlacementComponent.Kind(), &editorcomponent.PrefabPlacementState{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EntitySelectionComponent.Kind(), &editorcomponent.EntitySelectionState{SelectedIndex: -1, HoveredIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.EditorActionsComponent.Kind(), &editorcomponent.EditorActions{SelectLayer: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AreaDragStateComponent.Kind(), &editorcomponent.AreaDragState{EntityIndex: -1, PropertyEntityIndex: -1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.OverviewStateComponent.Kind(), &editorcomponent.OverviewState{Zoom: 1})
	_ = ecs.Add(w, sessionEntity, editorcomponent.UndoStackComponent.Kind(), &editorcomponent.UndoStack{Max: 100})
	_ = ecs.Add(w, sessionEntity, editorcomponent.ToolStrokeComponent.Kind(), &editorcomponent.ToolStroke{})
	_ = ecs.Add(w, sessionEntity, editorcomponent.AutotileStateComponent.Kind(), &editorcomponent.AutotileState{DirtyCells: map[int]map[int]struct{}{}, FullRebuild: map[int]bool{}})

	system := NewEditorAreaSystem("")
	system.Update(w)

	_, entities, _ := entitiesState(w)
	if len(entities.Items) != 1 {
		t.Fatalf("expected one transition entity, got %d", len(entities.Items))
	}
	created := entities.Items[0]
	if created.Type != "transition" {
		t.Fatalf("expected transition entity, got %q", created.Type)
	}
	if created.ID == "" {
		t.Fatal("expected autogenerated transition id")
	}
	if got := entityStringPropValue(created, "enter_dir"); got != "down" {
		t.Fatalf("expected default enter_dir down, got %q", got)
	}
	if got, ok := entityLayerIndex(created.Props); !ok || got != 1 {
		t.Fatalf("expected layer 1, got %d (ok=%t)", got, ok)
	}

	_, input, _ := rawInputState(w)
	_, pointer, _ := pointerState(w)
	input.LeftJustPressed = false
	input.LeftDown = true
	pointer.CellX = 5
	pointer.CellY = 6
	system.Update(w)

	created = entities.Items[0]
	if toFloat(created.Props["w"]) != 3*TileSize || toFloat(created.Props["h"]) != 3*TileSize {
		t.Fatalf("expected 3x3 tile area, got w=%v h=%v", created.Props["w"], created.Props["h"])
	}

	_, actions, _ := actionState(w)
	_, selection, _ := entitySelectionState(w)
	input.LeftDown = false
	input.LeftJustReleased = true
	system.Update(w)
	input.LeftJustReleased = false
	actions.TransitionID = "door_a"
	actions.TransitionToLevel = "zone_b"
	actions.TransitionLinkedID = "door_b"
	actions.TransitionEnterDir = "left"
	actions.ApplyTransitionFields = true
	system.Update(w)
	actions.TransitionToLevel = "zone_c"
	actions.ApplyTransitionFields = true
	system.Update(w)

	created = entities.Items[0]
	if created.ID != "door_a" {
		t.Fatalf("expected updated id, got %q", created.ID)
	}
	if got := entityStringPropValue(created, "to_level"); got != "zone_c.json" {
		t.Fatalf("expected normalized to_level zone_c.json, got %q", got)
	}
	if got := entityStringPropValue(created, "linked_id"); got != "door_b" {
		t.Fatalf("expected linked id door_b, got %q", got)
	}
	if got := entityStringPropValue(created, "enter_dir"); got != "left" {
		t.Fatalf("expected enter_dir left, got %q", got)
	}
	_, undo, _ := undoState(w)
	if len(undo.Snapshots) != 2 {
		t.Fatalf("expected two snapshots total (create + first property edit), got %d", len(undo.Snapshots))
	}
	if !selection.PropertySnapshotDone {
		t.Fatal("expected property snapshot flag to remain set after edits")
	}
}

func entityStringPropValue(item levels.Entity, key string) string {
	if item.Props == nil {
		return ""
	}
	value, _ := item.Props[key].(string)
	return value
}
